version: '2.7.0'
services:
  app:
    image: student-github-actions
    ports:
      - "8090:8090"
    environment:
      db-url: jdbc:postgresql://db:5043/students
      db-user: dockeruser
      db-password: dockerpassword
    depends_on:
      - db
    restart: always


  db:
    image: postgres
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: students
    ports:
      - "5043:5043"
    volumes:
      - C:\MEA ITaaS\postgres_container_data:/var/lib/postgresql/data
    restart: always